**1. Створення масивів**

Створіть (кожен пункт оцінюється в 0.5 бала):
- Масив зі списку `[5, 15, 25, 35, 45]`
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи `np.arange()`

In [ ]:
import numpy as np

# Зі списку
arr1 = np.array([5, 15, 25, 35, 45])
print("Масив зі списку:", arr1)

# Нулі
zeros = np.zeros(7)
print("Нулі:", zeros)

# Одиниці
ones = np.ones(6)
print("Одиниці:", ones)

# Діапазон
range_arr = np.arange(10, 20)
print("Від 10 до 19:", range_arr)

Масив зі списку: [ 5 15 25 35 45]
Нулі: [0. 0. 0. 0. 0. 0. 0.]
Одиниці: [1. 1. 1. 1. 1. 1.]
Від 10 до 19: [10 11 12 13 14 15 16 17 18 19]



---

**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [ ]:
arr = np.array([12, 24, 36, 48, 60])
display("Оригінальний масив:", arr)

# Множення на 2
multiplied = arr * 2
display("Помножений на 2:", multiplied)

# Додавання 10
added = arr + 10
display("Додано 10:", added)

# Квадрат
squared = arr ** 2
display("Квадрати:", squared)

# Квадратний корінь
sqrt = np.sqrt(arr)
display("Квадратний корінь:", sqrt.round(2))

'Оригінальний масив:'

array([12, 24, 36, 48, 60])

'Помножений на 2:'

array([ 24,  48,  72,  96, 120])

'Додано 10:'

array([22, 34, 46, 58, 70])

'Квадрати:'

array([ 144,  576, 1296, 2304, 3600])

'Квадратний корінь:'

array([3.46, 4.9 , 6.  , 6.93, 7.75])


---

**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [ ]:
data = np.array([18, 27, 33, 41, 52, 68, 79])

print("Дані:", data)
print("Середнє:", np.mean(data))
print("Мінімум:", np.min(data))
print("Максимум:", np.max(data))
print("Сума:", np.sum(data))

Дані: [18 27 33 41 52 68 79]
Середнє: 45.42857142857143
Мінімум: 18
Максимум: 79
Сума: 318



---

**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [ ]:
arr = np.array([15, 22, 35, 44, 58, 67])

# Індексація
print("Перший елемент:", arr[0])
print("Останній елемент:", arr[-1])
print("Елементи 1-3:", arr[1:4])

# Булева індексація
greater_than_40 = arr[arr > 40]
print("Більші за 40:", greater_than_40)

Перший елемент: 15
Останній елемент: 67
Елементи 1-3: [22 35 44]
Більші за 40: [44 58 67]



---


**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [ ]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [ ]:
print("Матриця:")
print(matrix)

# Форма
print("Форма:", matrix.shape)

# Перший рядок
print("Перший рядок:", matrix[0])

# Друга колонка (індекс 1)
print("Друга колонка:", matrix[:, 1])

# Сума
print("Сума всіх елементів:", matrix.sum())

# Середнє
print("Середнє:", matrix.mean())

Матриця:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Форма: (3, 3)
Перший рядок: [2 4 6]
Друга колонка: [ 4 10 16]
Сума всіх елементів: 90
Середнє: 10.0
